version: "3.3"

services:

    bot:
        build: .
        image: cerrrbot.image
        container_name: cerrrbot_app_container
        command: bash -c "python main.py"
        depends_on:
            - mongo_db
        links:
            - mongo_db
        volumes:
            - ~/.local/share/cerrrbot/data/:/home/data/
        environment:
            - DATA_DIRECTORY_ROOT=/home/data/
        networks:
            - cerrrbot-network
        restart: on-failure:15

    mongo_db:
        image: mongo:4.4.18
        volumes:
            - ~/.local/share/cerrrbot_data/db_data2/:/data/db/
        ports:
            - "6341:6341"
        networks:
            - cerrrbot-network

    redis_db:
        image: redis:latest
        command: --port 6667
        ports:
            - "6667:6667"
        networks:
            - cerrrbot-network

    celery:
        build: .
        image: cerrrbot_savmes_tasks_worker
        command: bash -c "celery -A tasks worker --loglevel=INFO"
        networks:
            - cerrrbot-network
        links:
            - redis_db

networks:
    cerrrbot-network:
      external: true